apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-devops-app
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-devops-app
  template:
    metadata:
      labels:
        app: my-devops-app
    spec:
      containers:
        - name: my-devops-app
          image: dydcjsrjaror/my-devops-app:e979debe973420bbf8811b2fb9cb90a20a4a3e5e
          ports:
            - containerPort: 80
