apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-devops-app
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-devops-app
  template:
    metadata:
      labels:
        app: my-devops-app
    spec:
      containers:
        - name: my-devops-app
          image: dydcjsrjaror/my-devops-app:2321b0a8ecc41b84664df08e466651f646ad0993
          ports:
            - containerPort: 80
