apiVersion: v1
kind: Service
metadata:
  name: my-devops-app
  namespace: default
spec:
  selector:
    app: my-devops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP